#!/usr/bin/env bash

# Exit immediately upon failure
set -euo pipefail

# Get the directory path of this script (should be root of the repo).
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

service="$DIR/source"
cd "$service"

out="$service/bin/Release/net5.0/linux-x64/publish/"

# Remove any old build artifacts
rm -rf "$out"

# Build in release mode
dotnet publish -c Release -r linux-x64 --no-self-contained

# Rsync up to server
server="webmaster@dev.apsim.info"
rsync -vaz "$out" "$server":/var/www/APSIM.Registration/

# Restart website on server
service_file="$DIR/APSIM.Registration.service"
rsync -vaz "$service_file" "$server":/home/webmaster/.config/systemd/user/
ssh "$server" systemctl --user daemon-reload
ssh "$server" systemctl --user restart APSIM.Registration
